require("sj.core.custom.Git.github")
require("sj.core.custom.Git.autoPush")
require("sj.core.custom.Git.smartCopyPaste")
require("sj.core.custom.Git.readmeGenerate")
require("sj.core.custom.Git.readmeGen2")
