require("sj.core.custom.insertMode")
require("sj.core.custom.others")
-- require("sj.core.custom.tmuxZsh")
-- require("sj.core.custom.tmuxZsh2")
require("sj.core.custom.checking-feature")
require("sj.core.custom.normalModeInInrsert")
require("sj.core.custom.html")
require("sj.core.custom.checking2")
require("sj.core.custom.JsTsPro")
require("sj.core.custom.Git")
require("sj.core.custom.TmuxZshCli")
